### ISSUE TITLE
Review calls of toHtml() with id

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-legacy#20]
The change to `toHtml()` in #16 caused problems in the legacy system (and might cause problems in other places, too):
When rendering the meta description of a course page, we go up to the parent and render that description instead. But when the parent (i.e. the course) doesn't have a description either, the Normalizer just returns the id as description (I assume, to handle the "go to parent" in course pages). Problem though: the id is a valid json (since it's an int) but can't be rendered by the editor renderers.
- In legacy, we still cover this with try-catch and just return the id as a string (after applying the quickfix)
- In kubernetes, we pass it to the renderer which will fail and therefore return an empty response

We should review whether there are other ints we try to render with `toHtml` that should be rendered. And probably fix meta description handling of courses since the id as a description doesn't make sense.

**Comment by hugotiburtino** [comment]
As far as I can understand, this issue is outdated due to the migration. Please reopen if I'm wrong
