### ISSUE TITLE
SEO(backlog): Image URLs – give URLs with keywords for images

### ISSUE THREAD

**Issue by MMitzko** [serlo/serlo.org-legacy#262]
This is a big task. Please make sure that you’ve got enough capacities in the Team and that there are no other important priorities before starting.

Vroni (SEO consulting) said that the images’ URL are very important for SEO. Improve the image URL structure to get URLs containing the image keywords and, also, the file path where they are deposited. For example, the URL should look like this:

- https://de.serlo.org/mathe/funktionen/funktionsbegriff.png

and not like this:

- https://assets.serlo.org/legacy/56fe95af016c7_bc84b18113f67b5ff4f2443da8eee5accd5ea901.png

**Comment by Knorrke** [comment]
Suggestion: The upload logic in our implementation for e.g. the image plugin should create this urls by appending `/filename` before the extension.

**Comment by elbotho** [comment]
Mostly solved in the new [frontend](https://github.com/serlo/frontend).
