### ISSUE TITLE
Missing e2e tests 

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-legacy#301]
- updating entity types (video, article, course...)
- create math puzzle and events
- taxonomy:
    - order taxonomy terms
    - viewing taxonomy
        - test title of pages
        - test rendering of breadcums
    - navigating through taxonomy via breadcums (backwards)
    - create other taxonomy types (cirriculum, ...)
    - update term or description of topic / topic folder
- Logout process, e.g:
    - given I am logged in as `user`
    - given I am on page `page`
    - when I click on button `Log Out`
    - then I am on page `page`
    - then I am logged out (e.g. button `Log In` occurs and we cannot open `/users/me`)

**Comment by elbotho** [comment]
e2e tests are now in https://github.com/serlo/frontend-e2e-tests/
