### ISSUE TITLE
Saving on staging crashes server

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-legacy#583]
If i try to save any article on staging, the requests timeout and other pages show a 504 / cloudflare notice that the server is down, this started to happen about after https://github.com/serlo/serlo.org/pull/570

**Comment by inyono** [comment]
It worked for me this time (both with and without review).

**Comment by Entkenntnis** [comment]
Trying to save trivial change here: https://de.serlo-staging.dev/entity/repository/add-revision/1875

Giving up after 3 unsuccessful tries. It's a non-converted article. Maybe this is causing the bug?

It worked with https://de.serlo-staging.dev/entity/repository/add-revision/25812 after 2 tries.

**Comment by elbotho** [comment]
Saving now uses new infrastructure.
