### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-legacy#590]
If someone wants to learn how to define CI workflows with GitHub Actions: https://github.com/serlo/serlo.org-database-layer/tree/main/.github has some patterns that we can also use in serlo.org (for example: setting up a database and waiting until it's ready). So, we could possibly:

- Run e2e tests (might run into some limits here, not sure)
- Run contract tests (this won't be needed soon-ish since the routes are moved to database layer)

**Comment by elbotho** [comment]
Since this repo is EOL we won't work on this.
